version: 2

jobs:
  build:
    docker:
      - image: python:3.6-alpine3.7

    steps:
      - run: "apk add --update libxslt libxslt-dev postgresql-client postgresql postgresql-dev libffi libffi-dev libxml2 libxml2-dev git build-base gcc cmake autoconf automake libtool"
      - checkout
      - run: "pip install -U -r requirements.txt"
      - run: "pip install -U -r requirements-test.txt"
      - run: "flake8 ultros_site/"

  deploy:
    docker:
      - image: docker:git

    steps:
      - checkout
      - setup_remote_docker
      - run: "sh docker/build.sh"

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build

      - deploy:
          requires:
            - build

          filters:
            branches:
              only:
                - master