version: 2

jobs:
  build:
    docker:
      - image: python:3.6-alpine3.7

    steps:
      - run: "apk add postgresql-client postgresql postgresql-dev libffi libffi-dev zlib zlib-dev git build-base gcc cmake autoconf automake libtool"
      - checkout
      - run: "pip install -U -r requirements.txt"
      - run: "pip install -U -r requirements-test.txt"
      - run: "flake8 ultros_site/"

  deploy:
    branches:
      only:
        - master

    docker:
      - image: docker:git

    steps:
      - checkout
      - setup_remote_docker
      - run: "sh docker/build.sh"
